name: Checkmarx AST Scan
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: ast-dsvw-tester
          base_uri: https://ast-master.dev.cxast.net/
          branch: ${{ github.base_ref	}}
          cx_tenant: galactica
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --threshold "sast-high=3;sca-high=1;kics-high=1"
